### ISSUE TITLE
Collaborating

### ISSUE THREAD

**Issue by auronvila** [tabbathacrouch/birthday-cards#2]
Hello @tabbathacrouch,

I came across your profile and am interested in collaborating on React or React Native projects. Could you please share any specific instructions or open issues that you'd like me to work on or improve?

Thank you!

**Comment by tabbathacrouch** [comment]
@auronvila 

I'm so sorry for not seeing this sooner!  I'll work on adding some tickets ASAP!  

General ideas/thoughts for the project:

1. Create a React-Native application that replaces my spreadsheet (google sheets) for listing birthday and number facts. 
2. Three Main stacks: **Facts, Calendar, Reminders**
3. The **Facts** stack will list all of the number facts I print onto note cards, allow editing or maybe just pull from a database? 
    - Eventually add "easy print" button --> Avery Printable Cards, Inkjet Printers, 120 Cards, 4.25 x 5.5, Heavyweight, Textured (3380)
4. The **Calendar** stack will highlight birthdays and allow users to add/edit birthday information (stored in database, perhaps firebase?)
5. The **Reminders** stack will serve a todo list. Add reminders to prepare envelopes, confirm addresses, and mark birthday cards as "sent".

**Comment by auronvila** [comment]
Thank You for providing information I try and contribute as much as I can.

Happy Coding!
